### ISSUE TITLE
Bug: Durability and enchantment

### ISSUE THREAD

**Issue by EGOIST1372** [gralp-1/dyeable-netherite#5]
Durability and enchantment of tools/armors get reset when you dye a tool/armor
Tool/armor get fully repair by dye???? why??? how a dye repair them?
Also since it uses crafting table it loses all enchantment that it has.

Also it overrides any texture/resource pack I have for netherite armor/tool pieces. 
It would be great if you could just add transparent texture for whole part of pieces and just add the dyed part into texture so it would be compatible with any custom texture/resource pack and just adds that colored part to texture.

thanks in advance

**Comment by gralp-1** [comment]
I can't solve the first issue at the moment because Minecraft doesn't support NBT crafting, meaning I can't make it keep durability or enchantments. There might be a library I'm not aware of for this. As for the second problem, that would completely change the way the mod works, you could do that with an optifine texture pack but it's not reasonable to do this for dyeable netherite.

**Comment by EGOIST1372** [comment]
@gralp-1 
I hope following links help you out

https://www.curseforge.com/minecraft/mc-mods/nbt-crafting
https://minecraft.fandom.com/wiki/Recipe#JSON_format
https://minecraft.fandom.com/wiki/Development_resources/Example_NBT_Class

https://github.com/Stevertus/objd_crafting
https://www.youtube.com/watch?v=jKre9Wl_5YA
